apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-production
resources:
  - ../../base
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: tqhung0105/argocd-lab-backend
    newName: docker.io/tqhung0105/argocd-lab-backend
    digest: sha256:dd53af672f69ac55c5dde0825876c3fcc6a64f05abaae83bdcbb2629d7ccc7e3
