apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-development
resources:
  - ../../base
replicas:
  - name: database
    count: 1
patches:
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: redis-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: minikube-sandbox/redis-password-development

images:
  - name: docker.io/library/redis
    newName: docker.io/library/redis
    digest: sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99
