apiVersion: v1
kind: Secret
metadata:
  name: github-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: *
  username: *
  password: *
