apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: demo-production
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 3Gi
    limits.cpu: "3.0"
    limits.memory: 6Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: demo-production
spec:
  limits:
    - default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: demo-development
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 3Gi
    limits.cpu: "3.0"
    limits.memory: 6Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: demo-development
spec:
  limits:
    - default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
