apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: tqhung0105/argocd-lab-frontend@sha256:46aa52dbe31688c3f83495e4960a642a94cd9390049cdc8b62920fba2175f515
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 1s }
        - setWeight: 50
        - pause: {}
        - setWeight: 100
